import AdminSidebar from "./AdminSidebar"
import React from "react";
import type { Metadata } from "next";

interface AdminDashboardLayoutprops {
    children : React.ReactNode
}

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

const AdminLayout = ({children} : AdminDashboardLayoutprops) => {
  return (
    <div className="overflow-height overflow-hidden flex  justify-between items-start">
        <div className="overflow-height lg:w-1/5 bg-emerald-600 text-white p-1 lg:p-5">
            <AdminSidebar />
        </div>
        <div className="overflow-height w-full overflow-y-auto  lg:w-4/5 p-1 lg:p-5 bg-white  ">
            {children}
        </div>
    </div>
  )
}

export default AdminLayout