import ArticleItem from "../components/articles/ArticleItem";
import type { Article } from "@/utils/types";
import type { Metadata } from "next";
import SearchArticleInput from "../components/articles/SearchArticleInput";
import Pagination from "../components/articles/Pagination";


const ArticlesPage = async () => {
  const res = await fetch("https://jsonplaceholder.typicode.com/posts");

if (!res.ok) {
    throw new Error("Failed to fetch articles");
  }

  const articles: Article[] = await res.json();

  return (
    <section className=" m-10">
      <h1 className="text-4xl font-bold text-center m-3 mb-12 text-gray-800">
        المقالات
      </h1>
<SearchArticleInput />
      <div className="grid grid-cols-1 sm:grid-cols-2 px-10 lg:grid-cols-3 gap-5">
        {articles.slice(0, 6).map((article) => (
          <ArticleItem key={article.id} article={article} />
        ))}
      </div>
      <Pagination />
    </section>

  );
};

export default ArticlesPage;


export const metadata: Metadata = {
  title: "Articles ",
  description: "Generated by create next app",
};
